#Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import os
import tensorflow as tf
from keras.preprocessing import image

#Preparation of Dataset

In [ ]:
os.chdir('D:\\Scene Analyzer_mini\\train')

In [ ]:
train_set=[]
ct=-1
for folder,sub_folders,files in os.walk('D:\\Scene Analyzer_mini\\train'):
    print(folder)
    for s in sub_folders:
        print(s)
    for f in files:
        buffer=image.load_img(folder+'\\'+f,target_size=(48,48))
        buffer=tf.keras.preprocessing.image.img_to_array(buffer)
        flattened=buffer.flatten()
        flattened=np.append(flattened,ct)
        train_set.append(flattened)
    ct+=1

D:\Scene Analyzer_mini\train
buildings
forest
glacier
mountain
sea
street
D:\Scene Analyzer_mini\train\buildings
D:\Scene Analyzer_mini\train\forest
D:\Scene Analyzer_mini\train\glacier
D:\Scene Analyzer_mini\train\mountain
D:\Scene Analyzer_mini\train\sea
D:\Scene Analyzer_mini\train\street


In [ ]:
dataset=pd.DataFrame(data=train_set)
dataset = dataset.sample(frac = 1)

In [ ]:
dataset.to_csv('train.csv')

In [ ]:
dataset

0      1      2      3      4      5      6      7      8      9     \
90   101.0  109.0  145.0   24.0   35.0   67.0  108.0  118.0  187.0  242.0   
149   38.0   80.0  130.0   49.0   91.0  141.0   57.0   97.0  149.0   53.0   
5    182.0  203.0  246.0  184.0  205.0  248.0  184.0  203.0  245.0  190.0   
92     6.0   17.0    1.0   46.0   63.0   21.0   82.0  108.0   35.0  133.0   
231  193.0  168.0  127.0  192.0  167.0  126.0  190.0  165.0  124.0  186.0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
45   221.0  227.0  239.0  223.0  228.0  221.0  244.0  248.0  255.0  228.0   
19   243.0  243.0  243.0  244.0  244.0  244.0  245.0  245.0  245.0  246.0   
89   130.0  116.0  115.0   11.0   14.0    5.0  244.0  223.0  220.0    9.0   
145   85.0  129.0  190.0   80.0  124.0  185.0   82.0  126.0  189.0   84.0   
181   83.0  142.0  198.0   85.0  142.0  197.0   85.0  141.0  198.0   83.0   

     ...   6903   6904   6905   6906   6907   6908   6909   6910   6911  6912  
90   ...    1.0    1.0    0.0    2.0    2.0    2.0    4.0    4.0    4.0   1.0  
149  ...  179.0  163.0   52.0  114.0  114.0   14.0  108.0  115.0   19.0   2.0  
5    ...  148.0  142.0  142.0  153.0  147.0  149.0  152.0  146.0  148.0   0.0  
92   ...   87.0  135.0   35.0   78.0  127.0   18.0   98.0  151.0   37.0   1.0  
231  ...   58.0   27.0   22.0   56.0   27.0   21.0   55.0   26.0   20.0   4.0  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   ...  
45   ...  142.0  160.0  182.0  144.0  165.0  186.0  143.0  164.0  185.0   0.0  
19   ...   33.0   33.0   33.0   35.0   35.0   35.0   31.0   31.0   31.0   0.0  
89   ...   66.0   80.0   27.0   88.0  101.0   55.0   74.0   88.0   29.0   1.0  
145  ...   60.0   58.0   46.0   42.0   42.0   30.0    1.0    6.0    0.0   2.0  
181  ...   65.0   79.0   56.0    9.0   20.0    3.0   67.0   77.0   43.0   3.0  

[300 rows x 6913 columns]

In [ ]:
os.chdir('D:\\Scene Analyzer_mini\\test')

In [ ]:
test_set=[]
ct=-1
for folder,sub_folders,files in os.walk('D:\\Scene Analyzer_mini\\train'):
    print(folder)
    for s in sub_folders:
        print(s)
    for f in files:
        buffer=image.load_img(folder+'\\'+f,target_size=(48,48))
        buffer=tf.keras.preprocessing.image.img_to_array(buffer)
        flattened=buffer.flatten()
        flattened=np.append(flattened,ct)
        test_set.append(flattened)
    ct+=1

D:\Expression Dataset_mini\test
angry
disgust
fear
happy
neutral
sad
surprise
D:\Expression Dataset_mini\test\angry
D:\Expression Dataset_mini\test\disgust
D:\Expression Dataset_mini\test\fear
D:\Expression Dataset_mini\test\happy
D:\Expression Dataset_mini\test\neutral
D:\Expression Dataset_mini\test\sad
D:\Expression Dataset_mini\test\surprise


In [ ]:
dataset=pd.DataFrame(data=test_set)
dataset = dataset.sample(frac = 1)

In [ ]:
dataset

0     1     2     3     4     5     6     7     8     9     ...  6903  \
94    182   194   182   182   184   183   194   187   195   192  ...   136   
190   162    82    23   157    75    15   158    73     9   173  ...   253   
242   167   163   164    71    67    68    28    23    27    20  ...   192   
88     45    35    23    47    38    23    47    38    23    45  ...    72   
277     5     4     0     4     3     0     2     2     0     2  ...   110   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
92    252   255   255   255   246   241   172   134   121   105  ...    62   
207    38    38    38    33    33    33    26    26    26    22  ...   188   
127    97    87    88    81    71    72   108    98    97   119  ...    62   
97    111   109    97   124   122   109   133   133   121   139  ...   129   
32     25    29    30    21    25    24    22    24    23    21  ...    71   

     6904  6905  6906  6907  6908  6909  6910  6911  6912  
94    108    96   136   124   124   209   209   219     1  
190   192   164   236   172   144   229   164   136     3  
242   196   109   216   223   128   195   205   106     4  
88     53    36    76    57    40    79    60    43     1  
277    52    74   126    55    89   185   104   145     5  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
92     65    58    69    68    64    65    59    59     1  
207   188   188   184   184   184   173   173   173     4  
127    61    57    60    61    56    55    56    51     2  
97     59    70   144    60    83   162    72   100     1  
32    134   165     0    73   105    36   119   153     0  

[350 rows x 6913 columns]

In [ ]:
dataset.to_csv('test.csv')

#Loading Train and Test Set

In [ ]:
dataset=pd.read_csv('train.csv')
x_train=dataset.iloc[:,1:-1].values
y_train=dataset.iloc[:,-1].values

In [ ]:
x_train

array([[101., 109., 145., ...,   4.,   4.,   4.],
       [ 38.,  80., 130., ..., 108., 115.,  19.],
       [182., 203., 246., ..., 152., 146., 148.],
       ...,
       [130., 116., 115., ...,  74.,  88.,  29.],
       [ 85., 129., 190., ...,   1.,   6.,   0.],
       [ 83., 142., 198., ...,  67.,  77.,  43.]])

In [ ]:
dataset=pd.read_csv('test.csv')
x_test=dataset.iloc[:,1:-1].values
y_test=dataset.iloc[:,-1].values

#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

#Grid Search Function

In [ ]:
#TLE in logistic regression
from sklearn.model_selection import GridSearchCV
def grid_fun(parameters,classifier):
  grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
  grid_search.fit(x_train, y_train)
  best_accuracy = grid_search.best_score_
  best_parameters = grid_search.best_params_
  print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
  return best_parameters

#K-Fold Cross Validation Function

In [ ]:
from sklearn.model_selection import cross_val_score
def KFCV(classifier):
  accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)
  print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
  print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

#Model List

In [ ]:
# from sklearn.linear_model import LogisticRegression
# classifier = LogisticRegression(max_iter=500) 
## parameters = [{'C': [0.25,0.5,1], 'solver': ['lbfgs'],'max_iter':[500]}] 
## print(grid_fun(parameters,classifier)) #TLE
## <--- LogisticRegression: 37% (manually tested) ---> ##
# classifier.fit(x_train,y_train)
#####################################################
# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier()      
# parameters=[{'n_neighbors':[5,10,20,30],'weights':['uniform','distance'],'metric':['minkowski'],'p':[1,2]}]  
# print(grid_fun(parameters,classifier))        
## <--- KNN: 45% Accuracy ---> ##
## <--- Paramters: 'metric': 'minkowski', 'n_neighbors': 5, 'p': 1, 'weights': 'distance' ---> ##
# classifier.fit(x_train,y_train)
#######################################################
# from sklearn.ensemble import RandomForestClassifier
# classifier = RandomForestClassifier()
# parameters=[{'n_estimators':[100,150,200],'criterion':['gini','entropy']}]  
# print(grid_fun(parameters,classifier))
## <--- RandomForest: 56.33% Accuracy ---> ##
## <--- Parameters: 'criterion': 'gini', 'n_estimators': 100 ---> ##
# classifier.fit(x_train, y_train)
#######################################################
# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()
# KFCV(classifier)
## <--- NaiveBayes: 51% Default Parameters ---> ##
# classifier.fit(x_train, y_train) 
#######################################################
# from sklearn.tree import DecisionTreeClassifier
# classifier = DecisionTreeClassifier()
# parameters=[{'splitter':['best','random'],'criterion':['gini','entropy']}]  
# print(grid_fun(parameters,classifier))
## <--- Decision Tree: 37.3% Accuracy ---> ##
## <--- Parameters: 'criterion': 'entropy', 'splitter': 'random' ---> ##
# classifier.fit(x_train, y_train) 
#######################################################
from sklearn.svm import SVC
# classifier = SVC()
# parameters = [{'C': [0.25, 0.5, 0.75, 1], 'kernel': ['linear'],'decision_function_shape':['ovo', 'ovr']},
#               {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,'auto'],'decision_function_shape':['ovo', 'ovr']},
#               {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['poly'],'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9,'auto'],'decision_function_shape':['ovo', 'ovr']},
#               {'C': [0.25, 0.5, 0.75, 1], 'kernel': ['sigmoid'],'decision_function_shape':['ovo', 'ovr']}]
# print(grid_fun(parameters,classifier))
## <--- KernelSVM: 57% ---> ##
## <--- Paramaters:'C': 1, 'decision_function_shape': 'ovo', 'gamma': 'auto', 'kernel': 'rbf' ---> ##
classifier=SVC(C=1,decision_function_shape='ovo',gamma='auto',kernel='rbf')
classifier.fit(x_train, y_train) 
#######################################################
# from xgboost import XGBClassifier
# classifier = XGBClassifier()
# KFCV(classifier)
## <--- XGBoost: 50% Accuracy ---> ##
## <--- All Defaults ---> ##
# classifier.fit(x_train, y_train) 
#######################################################

SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#Predicting Test Cases

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('{}%'.format(accuracy_score(y_test, y_pred)*100))

[[3 0 3 1 2 1]
 [1 5 0 0 1 3]
 [2 0 4 2 1 1]
 [2 0 0 7 1 0]
 [1 1 1 2 5 0]
 [1 1 0 0 2 6]]
50.0%


#Single Prediction

In [ ]:
path=''#specify your image path 
test_image=image.load_img(path,target_size=(48,48))
test_image=tf.keras.preprocessing.image.img_to_array(test_image)
test_image=test_image.flatten()
test_image=np.expand_dims(test_image,axis=0)
test_image=sc.transform(test_image)
val=classifier.predict(test_image)

if val==0:
  print('Buildings')
elif val==1:
  print('Forest')
elif val==2:
  print('Glacier')
elif val==3:
  print('Mountain')
elif val==4:
  print('Sea')
else:
  print('Street')